### ISSUE TITLE
Images do not work

### ISSUE THREAD

**Issue by thegit456** [nhmkdev/cardmaker#116]
I am making a card game and I want to make the cards more efficiently by making them in a excel spreadsheet. I used the tutorial provided and in the "image" collumn I placed the image path. When I went to card maker and I entered "@[image]" nothing happened. It works with everything else but not the images... please help

**Comment by nhmkdev** [comment]
Couple of questions:
* Which version are you running?
* What operating system are you running?
* Is your element Type set to Graphic? By default it's generally Text.
* If Graphic, can you enter the value from the image column instead of `@[image]` just to prove the pathing works?

You can use relative paths or full paths. I recommend relative but it requires laying out files/folders to match.
Examples:
* Relative path: `images\biohazard.png`
* Full Path: `e:\github\cardmaker\cardmaker\bin\release\sample\images\biohazard.png`

Also, if you have other issues/questions I suggest joining the board game geek guild for this application: https://boardgamegeek.com/guild/2250

**Comment by nhmkdev** [comment]
Stale, closing out.
