### ISSUE TITLE
[Annoyance] Layout starts out completely expanded

### ISSUE THREAD

**Issue by MarkVabulas** [nhmkdev/cardmaker#147]
Can we implement the changes which I already did here: 
https://github.com/nhmkdev/cardmaker/commit/1f3b5a45ff7bab0c94ec94f5504b2b26489b7c06

**Comment by nhmkdev** [comment]
🤣

I'll meet you half way and probably just add 2 things:
* The project will save the expanded/unexpanded state of the child nodes
* Add a button/menu item that collapses them to just the layout names

**Comment by MarkVabulas** [comment]
That's a whole lot more work!  I'm just suggesting changing the default, I don't think people need to see the list of attached things from the get-go, but it's easy to just open them :)  

(And the lack of a + sign is an indicator that it doesn't have a spreadsheet attached)

**Comment by nhmkdev** [comment]
Added persistence to projects with this change: https://github.com/nhmkdev/cardmaker/commit/073c3854a6b19c7eb3a4b3a4229a8a2b9a0f9ecd

Should be backwards compatible with projects without the field. While there's plenty of null and otherwise checks it's possible that some edge case will break things. 😨 

This will be included in the next pre-release... which is going include a ton of changes.

**Comment by MarkVabulas** [comment]
Works great so far!  Can close this now :)

**Comment by nhmkdev** [comment]
Supported with https://github.com/nhmkdev/cardmaker/releases/tag/v.1.4.0.0-unstable.v.a2
