### ISSUE TITLE
[Enhanement] Use the lua language for scripts in elements

### ISSUE THREAD

**Issue by Jummit** [nhmkdev/cardmaker#62]
Lua wouldn't be to difficult to implement in C# (I think) and is a lot more powerful than writing an own language.

Maybe take a look [here](http://nlua.org/)

**Comment by nhmkdev** [comment]
[Moonsharp](http://www.moonsharp.org/) would be an option too. It would likely have the same (minor?) issues that the current JavaScript support has. If there is a lot of interest I could investigate it. 

For me, the 'Incept' script/macro language was created to avoid having a significant hurdle for setting up the most basic things. I wouldn't really consider removing it as it's still the quickest way for me to develop game components (but that's just because it's what I am used to).

**Comment by nhmkdev** [comment]
Closing this out as no other interest was mentioned.
