### ISSUE TITLE
Card Count showing as "1/1162167" with CSV Reference

### ISSUE THREAD

**Issue by jstevenson** [nhmkdev/cardmaker#68]
For some reason the LayoutManager.Instance.ActiveDeck value isn't being set even though I have a referenced CSV file. The 2nd row of the CSV file (the first with data) is being used within the canvas, so it is reading the file properly.

**Comment by nhmkdev** [comment]
Is there anything unique about the CSV file? Can you attach it or email it so I can debug the issue? If you'd rather not (perfectly understandable) how many rows are in it and are there any special characters or other characteristics? Also which editor did you create the CSV with?

Thanks!

**Comment by jstevenson** [comment]
This file is a CSV export from a Google Sheet. It is just game data, and my families preferences, so nothing private.

Thanks, Jim

[Games.zip](https://github.com/nhmkdev/cardmaker/files/3238188/Games.zip)

**Comment by nhmkdev** [comment]
Good news! The problem is that the first column of the reference should be a count column indicating how many copies of the row/card you need. Your first column is an id field so it's adding all of the ids up as card counts to give you the crazy number.

https://github.com/nhmkdev/cardmaker/wiki/user-references-basic#reference-file

**Comment by jstevenson** [comment]
Doh, thank you very much! CardMaker is a cool piece of software :)
