### ISSUE TITLE
Fonts installed on machine not showing up in Card Maker

### ISSUE THREAD

**Issue by arcandio** [nhmkdev/cardmaker#71]
First off, awesome program, I was an idiot for doing this stuff manually before.

The only problem I have so far is that some fonts I want to use aren't available in Card Maker's font dropdown. Here's a set I have installed but don't show up: https://www.reddit.com/r/UnearthedArcana/comments/3vpphx/5e_font_package_embeddable_cc_edition/

I don't know if it's a problem with the OTF format or if it's some other issue. I'm able to open fonts and examine the flags or export to other formats if that helps me get the project done or test solutions.

**Comment by arcandio** [comment]
* Build: 1.0.0.2
* OS: Windows 10 home 1903

**Comment by nhmkdev** [comment]
Yea sadly the renderer that I use (GDI+) does not support Open Type fonts. I see there are some projects out there that may be able to help with this but I'd have to investigate and see if they are reasonably functional. Apparently there are tools to convert OTF to TTF so that's a short term option too ... if that even works right!

**Comment by arcandio** [comment]
Thanks for the quick reply, that makes sense. I can try converting them and see if they show up.

**Comment by nhmkdev** [comment]
Closing out old bugs/issues.
