### ISSUE TITLE
[BUG] Grouped Variable Logic does not work as expected

### ISSUE THREAD

**Issue by xetra11** [nhmkdev/cardmaker#84]
Version: v1.1.0.0 V.A11-2

Trying this statement:
```#(if [@[critmod];@[reachmod];@[damage];@[lifepoints]] != #empty then true else false)#```
It should resolve into `true` if any of the @ references has a value - `false` if none has any.

For `@[damage]` having a value of `1` the expression resolves to `false`. I expected it to resolve to `true`. Am I too tired to use booleans properly?

**Comment by nhmkdev** [comment]
That's not quite how the grouped logic check works.

From the manual:
> You can use the if statement with groups. The x and y values listed
> above can be formatted as:
> [val1;val2;val3]
> Allowing multiple items to be compared to multiple other items. The x set
> of strings is sought in the y set. The comparison is successful if all of the
> items in x exist in y. (the y set is not checked for existing in x)

I wouldn't bother with groups for that. I think this would accomplish what you want:
`#(if @[critmod]@[reachmod]@[damage]@[lifepoints] != #empty then true else false)#`

Basically it would be an empty string if they are all blank. Otherwise it will be non-empty.
